import 'package:cmed_lib_flutter/common/helper/date_utils.dart';
import 'package:cmed_lib_flutter/common/widget/app_dialog.dart';
import 'package:cmed_lib_flutter/common/widget/basic_app_bar.dart';
import 'package:cmed_lib_flutter/page/health_screening/dto/measurement_dto.dart';
import 'package:cmed_lib_flutter/page/health_screening/repository/screening_report_repository.dart';
import 'package:cmed_lib_flutter/page/health_screening/health_screening_home_i18n.dart';
import 'package:cmed_lib_flutter/page/health_screening/npage/manual/npage/muac/muac_input_logic.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_rapid/flutter_rapid.dart';
import 'package:flutter_svg/svg.dart';
import 'package:get/get.dart';

import 'package:cmed_lib_flutter/common/helper/text_utils.dart';
import 'package:cmed_lib_flutter/common/widget/cmed_birth_date_picker.dart';
import 'package:cmed_lib_flutter/common/widget/cmed_text_field.dart';
import 'package:cmed_lib_flutter/common/widget/cmed_white_elevated_button.dart';
import 'package:themed/themed.dart';

import 'hemoglobin_input_logic.dart';


class HemoglobinInputView extends RapidView<HemoglobinInputLogic> {
  static String routeName = '/HemoglobinInputView';

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: (){
        FocusScope.of(context).requestFocus(FocusNode());
      },
      child: Scaffold(
        appBar: controller.isNestedRoute? null:BasicAppBar('Hemoglobin'.tr),
        body: SafeArea(
          child: SingleChildScrollView(
            child: Form(
              key: controller.screeningReportFormKey,
              child: Column(
                children: [
                  Padding(
                    padding: const EdgeInsets.all(12.0),
                    child: Card(
                      shadowColor: Theme.of(context).primaryColor,
                      elevation: 2,
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: <Widget>[
                            const SizedBox(
                              height: 4,
                            ),
                            Padding(
                              padding:
                              const EdgeInsets.symmetric(horizontal: 2.0),
                              child: Text(
                                'label_select_date'.tr,
                                style: CMEDTextUtils.inputTextLabelStyle,
                              ),
                            ),
                            CMEDBirthDatePicker(
                              bottomMargin: 12,
                              title:  controller.dateController.text.isEmpty ? null : CustomDateUtils.formatDatePicker(controller.dateController.text),
                              isShowCurrentDate: true,
                              onDateSelect: (DateTime date) {
                                controller.dateController.text = date.millisecondsSinceEpoch.toString();
                              },
                            ),

                            const SizedBox(
                              height: 8,
                            ),
                            Padding(
                              padding:
                              const EdgeInsets.symmetric(horizontal: 2.0),
                              child: Text('Hemoglobin measure'.tr,
                                style: CMEDTextUtils.inputTextLabelStyle,
                              ),
                            ),
                            CMEDTextField(
                                'Input measure'.tr,
                                autovalidateMode: AutovalidateMode.onUserInteraction,
                                keyboardType: const TextInputType.numberWithOptions(decimal: true, signed: false),
                                inputFormatters: [FilteringTextInputFormatter.allow(RegExp(r'^\d+\.?\d{0,2}'))],
                                textEditingController: controller.hemoglobinController,
                                onSaved: (value) {}, onValidator: (value) {
                              return controller.validateHemoglobin(value!);
                            }),

                            const SizedBox(
                              height: 4,
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(
                        vertical: 8.0, horizontal: 16.0),
                    child: Stack(
                      children: [
                        Row(
                          children: [
                            Expanded(
                              child: CMEDWhiteElevatedButton(
                                'label_enter'.tr,
                                    () => {
                                  if (controller.isValidInput())
                                    AppDialogs.showDoubleButtonDialog(
                                        'label_measurement_store_warning'.tr,
                                        bodyText: controller.getInputText(),
                                        onPositiveButtonClick: () => {
                                          controller.sendMeasurement(),
                                        }),
                                },
                              ),
                            ),
                          ],
                        ),
                        Obx(() {
                          if (controller.isSuccess.value) {
                            controller.isSuccess.value = false;
                            Future.delayed(Duration.zero, () async {
                              Get.offNamed('/screening_report_result_details',
                                  arguments: [
                                    {
                                      "screeningReport":
                                      controller.screeningReport.value
                                    }
                                  ]);
                            });
                          }
                          return Visibility(
                              visible: controller.isLoading.value,
                              child:
                              const Center(child: CircularProgressIndicator()));
                        }),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Map<String, Map<String, String>> getI18n() {
    return {
      "en_US": {
        "Normal": "Normal",
        "Your child’s HB% level is normal now. Continue breastfeeding up to 2 years and give daily rice/porridge with meat, fish, egg yolk, lentils, vegetables, plus vitamin C foods (orange, guava, tomato) .After 1 year, give deworming medicine (as advised by doctor).": "Your child’s HB% level is normal now. Continue breastfeeding up to 2 years and give daily rice/porridge with meat, fish, egg yolk, lentils, vegetables, plus vitamin C foods (orange, guava, tomato) .After 1 year, give deworming medicine (as advised by doctor).",
        "Mild": "Mild",
        "Your child has mild anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "Your child has mild anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.",
        "Moderate": "Moderate",
        "Your child has moderate anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "Your child has moderate anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.",
        "Severe": "Severe",
        "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Continue breastfeeding and give iron-rich foods  with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.": "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Continue breastfeeding and give iron-rich foods  with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.",
        "Your child’s HB% level is normal. Give 3 meals and 1–2 healthy snacks daily with iron-rich foods & Add vitamin C foods  with meals.Avoid junk food, and excess cow’s milk .Maintain handwashing, safe water, and good hygiene, and give deworming medicine every 6 months as advised by the doctor.": "Your child’s HB% level is normal. Give 3 meals and 1–2 healthy snacks daily with iron-rich foods & Add vitamin C foods  with meals.Avoid junk food, and excess cow’s milk .Maintain handwashing, safe water, and good hygiene, and give deworming medicine every 6 months as advised by the doctor.",
        "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.": "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.",
        "Your child’s Hb% level is normal. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods  Limit junk food, tea, and excess cow’s milk. Maintain good hygiene, handwashing, safe drinking water, and give deworming medicine as advised by the doctor.": "Your child’s Hb% level is normal. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods  Limit junk food, tea, and excess cow’s milk. Maintain good hygiene, handwashing, safe drinking water, and give deworming medicine as advised by the doctor.",
        "Your child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "Your child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.",
        "Your child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "Your child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.",
        "Your child's  Hb% level is normal। Encourage 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods.  Maintain good hygiene, regular physical activity, and follow deworming advice as recommended by the doctor. ": "Your child's  Hb% level is normal। Encourage 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods.  Maintain good hygiene, regular physical activity, and follow deworming advice as recommended by the doctor. ",
        "Your  child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement": "Your  child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement",
        "Your  child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement": "Your  child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement",
        "Your  child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.": "Your  child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.",
        "Your blood hb% level is normal. Maintain a balanced diet with iron-rich foods &  vitamin C foods. Practice good hygiene, stay physically active, and follow deworming advice if recommended by your doctor.": "Your blood hb% level is normal. Maintain a balanced diet with iron-rich foods &  vitamin C foods. Practice good hygiene, stay physically active, and follow deworming advice if recommended by your doctor.",
        "Your hemoglobin is Mild high than normal. Stay well-hydrated, avoid unnecessary iron supplements, and consult a doctor for proper evaluation.": "Your hemoglobin is Mild high than normal. Stay well-hydrated, avoid unnecessary iron supplements, and consult a doctor for proper evaluation.",
        "You have moderate anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.": "You have moderate anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.",
        "You have severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Eat iron-rich foods  with vitamin C foods. Take medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.": "You have severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Eat iron-rich foods  with vitamin C foods. Take medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.",
        "You have mild anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.": "You have mild anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.",
        "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods . Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.": "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods . Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.",
        "You have mild anemia. Eat a balanced diet with iron-rich foods & vitamin C foods . Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "You have mild anemia. Eat a balanced diet with iron-rich foods & vitamin C foods . Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.",
        "You have moderate anemia. Eat a balanced diet with iron-rich foods & vitamin C foods .Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "You have moderate anemia. Eat a balanced diet with iron-rich foods & vitamin C foods .Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.",
        "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods  along with vitamin C foods. Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods  along with vitamin C foods. Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.",
        "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods .Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.": "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods .Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.",
        "You have mild anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "You have mild anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.",
        "You have moderate anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "You have moderate anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.",
        "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.",
        "You have Moderate  anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "You have Moderate  anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.",
        "You have severe anemia which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "You have severe anemia which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor."
      },
      "bn_BD": {
        "Normal": "স্বাভাবিক",
        "Your child’s HB% level is normal now. Continue breastfeeding up to 2 years and give daily rice/porridge with meat, fish, egg yolk, lentils, vegetables, plus vitamin C foods (orange, guava, tomato) .After 1 year, give deworming medicine (as advised by doctor).": "আপনার শিশুর রক্তের আয়রনের মাত্রা  এখন স্বাভাবিক।২ বছর পর্যন্ত মায়ের দুধ চালিয়ে যান এবং প্রতিদিন ভাত/খিচুড়ির সাথে মাংস, মাছ, ডিমের কুসুম, ডাল, শাকসবজি ও ভিটামিন–সি সমৃদ্ধ খাবার (কমলা, পেয়ারা, টমেটো) দিন.১ বছরের পর ডাক্তারদের পরামর্শ অনুযায়ী কৃমির ওষুধ দিন।",
        "Mild": "মৃদু উচ্চ",
        "Your child has mild anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "আপনার শিশুর হালকা রক্তাল্পতা হয়েছে। দুই বছর পর্যন্ত বুকের দুধ চালিয়ে যান এবং প্রতিদিন ভাত/খিচুড়ির সাথে আয়রন জাতীয় এবং ভিটামিন সি জাতীয় খাবার দিন,  ডাক্তার যেভাবে আয়রন সিরাপ দিয়েছেন নিয়মিত দিন, পরিষ্কার-পরিচ্ছন্নতা ও নিরাপদ পানি নিশ্চিত করুন, ১ বছর বয়সের পর কৃমির ওষুধ দিন এবং ২–৩ মাস পর আবার Hb পরীক্ষা করুন উন্নতি দেখার জন্য।",
        "Moderate": "মাঝারি উচ্চ",
        "Your child has moderate anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "আপনার শিশুর মাঝারি পরিমানে রক্তাল্পতা হয়েছে। দুই বছর পর্যন্ত বুকের দুধ চালিয়ে যান এবং প্রতিদিন ভাত/খিচুড়ির সাথে আয়রন জাতীয় এবং ভিটামিন সি জাতীয় খাবার দিন,  ডাক্তার যেভাবে আয়রন সিরাপ দিয়েছেন নিয়মিত দিন, পরিষ্কার-পরিচ্ছন্নতা ও নিরাপদ পানি নিশ্চিত করুন, ১ বছর বয়সের পর কৃমির ওষুধ দিন এবং ২–৩ মাস পর আবার Hb পরীক্ষা করুন উন্নতি দেখার জন্য।",
        "Severe": "মাত্রাতিরিক্ত",
        "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Continue breastfeeding and give iron-rich foods  with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.": "আপনার শিশুর গুরুতর রক্তাল্পতা হয়েছে, যা বিপজ্জনক এবং জরুরি হাসপাতালে চিকিৎসার প্রয়োজন। ডাক্তার রক্ত দেওয়া (ট্রান্সফিউশন) এবং আয়রন চিকিৎসার পরামর্শ দিতে পারেন। বুকের দুধ চালিয়ে যান এবং আয়রন সমৃদ্ধ খাবার দিন  সাথে ভিটামিন C সমৃদ্ধ খাবার। ডাক্তার যে ওষুধ দেবেন তা নিয়ম মেনে দিন এবং সব ফলো-আপে যান। ডাক্তারের পরামর্শ অনুযায়ী Hb আবার পরীক্ষা করুন।",
        "Your child’s HB% level is normal. Give 3 meals and 1–2 healthy snacks daily with iron-rich foods & Add vitamin C foods  with meals.Avoid junk food, and excess cow’s milk .Maintain handwashing, safe water, and good hygiene, and give deworming medicine every 6 months as advised by the doctor.": "আপনার শিশুর Hb% স্বাভাবিক। প্রতিদিন ৩টি প্রধান খাবার এবং ১–২টি স্বাস্থ্যকর নাস্তা দিন,  যা আয়রন সমৃদ্ধ এবং  ভিটামিন সি সমৃদ্ধ খাবার । জাঙ্ক ফুড,  এবং অতিরিক্ত গরুর দুধ  এড়িয়ে চলুন। নিয়মিত হাত ধোয়া, নিরাপদ পানি এবং সঠিক স্বাস্থ্যবিধি বজায় রাখুন এবং ডাক্তারদের পরামর্শ অনুযায়ী প্রতি ৬ মাসে কৃমির ওষুধ দিন।",
        "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.": "আপনার শিশুর গুরুতর রক্তাল্পতা হয়েছে, যা বিপজ্জনক এবং জরুরি হাসপাতালে চিকিৎসার প্রয়োজন। ডাক্তার রক্ত দেওয়া (ট্রান্সফিউশন) এবং আয়রন চিকিৎসার পরামর্শ দিতে পারেন।আয়রন  সমৃদ্ধ খাবার দিন সাথে ভিটামিন সি সমৃদ্ধ খাবার। ডাক্তার যে ওষুধ দেবেন তা নিয়ম মেনে দিন এবং সব ফলো-আপে যান। ডাক্তারের পরামর্শ অনুযায়ী Hb আবার পরীক্ষা করুন।",
        "Your child’s Hb% level is normal. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods  Limit junk food, tea, and excess cow’s milk. Maintain good hygiene, handwashing, safe drinking water, and give deworming medicine as advised by the doctor.": "আপনার শিশুর Hb% স্বাভাবিক। প্রতিদিন ৩টি প্রধান খাবার এবং ১–২টি স্বাস্থ্যকর নাস্তা দিন, সঙ্গে এমন খাবার যা আয়রন যুক্ত এবং   ভিটামিন সি সমৃদ্ধ।জাঙ্ক ফুড, চা এবং অতিরিক্ত গরুর দুধ ) এড়িয়ে চলুন। নিয়মিত হাত ধোয়া, নিরাপদ পানি এবং সঠিক স্বাস্থ্যবিধি বজায় রাখুন এবং ডাক্তারদের পরামর্শ অনুযায়ী প্রতি ৬ মাসে কৃমির ওষুধ দিন।",
        "Your child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "আপনার শিশুর হালকা রক্তাল্পতা হয়েছে।  প্রতিদিন ৩টি প্রধান খাবার এবং ১–২টি স্বাস্থ্যকর নাস্তা দিন, সঙ্গে এমন খাবার যা আয়রন যুক্ত এবং   ভিটামিন সি যুক্ত।   ডাক্তার যেভাবে আয়রন সিরাপ দিয়েছেন নিয়মিত দিন, পরিষ্কার-পরিচ্ছন্নতা ও নিরাপদ পানি নিশ্চিত করুন, ১ বছর বয়সের পর কৃমির ওষুধ দিন এবং ২–৩ মাস পর আবার Hb পরীক্ষা করুন উন্নতি দেখার জন্য।",
        "Your child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "আপনার শিশুর মাঝারি পরিমানে রক্তাল্পতা হয়েছে।প্রতিদিন ৩টি প্রধান খাবার এবং ১–২টি স্বাস্থ্যকর নাস্তা দিন, সঙ্গে এমন খাবার যা আয়রন যুক্ত এবং ভিটামিন সি যুক্ত।  ডাক্তার যেভাবে আয়রন সিরাপ দিয়েছেন নিয়মিত দিন, পরিষ্কার-পরিচ্ছন্নতা ও নিরাপদ পানি নিশ্চিত করুন, ১ বছর বয়সের পর কৃমির ওষুধ দিন এবং ২–৩ মাস পর আবার Hb পরীক্ষা করুন উন্নতি দেখার জন্য।",
        "Your child's  Hb% level is normal। Encourage 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods.  Maintain good hygiene, regular physical activity, and follow deworming advice as recommended by the doctor. ": "আপনার সন্তানের Hb% স্বাভাবিক। প্রতিদিন ৩টি সুষম খাবার এবং স্বাস্থ্যকর নাস্তা দিন, যা আয়রন সমৃদ্ধ খাবার ও ভিটামিন C সমৃদ্ধ। নিয়মিত হাত ধোয়া, পরিষ্কার-পরিচ্ছন্নতা, নিয়মিত শারীরিক ক্রিয়াকলাপ বজায় রাখুন এবং ডাক্তার পরামর্শ অনুযায়ী কৃমির ওষুধ দিন।",
        "Your  child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement": "আপনার সন্তানের হালকা রক্তাল্পতা রয়েছে। প্রতিদিন ৩টি সুষম খাবার এবং স্বাস্থ্যকর নাস্তা দিন, সঙ্গে  আয়রন সমৃদ্ধ ও  ভিটামিন C সমৃদ্ধ খাবার দিন ।  ডাক্তার নির্দেশ অনুযায়ী আয়রন সিরাপ বা সাপ্লিমেন্ট দিন। ভালো পরিচ্ছন্নতা, নিরাপদ পানি এবং কৃমির ওষুধ নিশ্চিত করুন এবং শিশুর বৃদ্ধি পর্যবেক্ষণ করুন। ২–৩ মাস পরে Hb পরীক্ষা করুন উন্নতি দেখার জন্য।",
        "Your  child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement": "আপনার সন্তানের মাঝারি পরিমানে রক্তাল্পতা রয়েছে। প্রতিদিন ৩টি সুষম খাবার এবং স্বাস্থ্যকর নাস্তা দিন, সঙ্গে আয়রন সমৃদ্ধ ও  ভিটামিন C সমৃদ্ধ খাবার দিন ।  ডাক্তার নির্দেশ অনুযায়ী আয়রন সিরাপ বা সাপ্লিমেন্ট দিন। ভালো পরিচ্ছন্নতা, নিরাপদ পানি এবং কৃমির ওষুধ নিশ্চিত করুন এবং শিশুর বৃদ্ধি পর্যবেক্ষণ করুন। ২–৩ মাস পরে Hb পরীক্ষা করুন উন্নতি দেখার জন্য।",
        "Your  child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.": "আপনার সন্তানের গুরুতর রক্তাল্পতা হয়েছে, যা বিপজ্জনক এবং জরুরি হাসপাতালে চিকিৎসার প্রয়োজন। ডাক্তার রক্ত দেওয়া (ট্রান্সফিউশন) এবং আয়রন চিকিৎসার পরামর্শ দিতে পারেন।আয়রন  সমৃদ্ধ খাবার দিন সাথে ভিটামিন সি সমৃদ্ধ খাবার। ডাক্তার যে ওষুধ দেবেন তা নিয়ম মেনে দিন এবং সব ফলো-আপে যান। ডাক্তারের পরামর্শ অনুযায়ী Hb আবার পরীক্ষা করুন।",
        "Your blood hb% level is normal. Maintain a balanced diet with iron-rich foods &  vitamin C foods. Practice good hygiene, stay physically active, and follow deworming advice if recommended by your doctor.": "আপনার  রক্তে আয়রনের পরিমান স্বাভাবিক . প্রতিদিন ৩টি সুষম খাবার এবং স্বাস্থ্যকর নাস্তা   যা আয়রন  সমৃদ্ধ ও ভিটামিন সি সমৃদ্ধ । নিয়মিত হাত ধোয়া, পরিষ্কার-পরিচ্ছন্নতা বজায় রাখুন, নিয়মিত শারীরিক কার্যক্রম করান এবং ডাক্তার পরামর্শ অনুযায়ী কৃমির ওষুধ দিন।",
        "Your hemoglobin is Mild high than normal. Stay well-hydrated, avoid unnecessary iron supplements, and consult a doctor for proper evaluation.": "আপনার রক্তাল্পতা (হালকা) রয়েছে । সুষম খাবার খান, যা আয়রন সমৃদ্ধ খাবার ও ভিটামিন C সমৃদ্ধ খাবার ।ডাক্তারের পরামর্শ অনুযায়ী আয়রন সাপ্লিমেন্ট নিন। পরিষ্কার পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন এবং ডাক্তার নির্দেশ অনুযায়ী কৃমির ওষুধ নিন। ২–৩ মাস পর Hb পরীক্ষা করুন উন্নতি পর্যবেক্ষণের জন্য।",
        "You have moderate anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.": "আপনার রক্তাল্পতা মাঝারি পরিমানে রয়েছে । সুষম খাবার খান, যা আয়রন সমৃদ্ধ খাবার ও ভিটামিন সি সমৃদ্ধ খাবার ।ডাক্তার পরামর্শ অনুযায়ী আয়রন সাপ্লিমেন্ট নিন। পরিষ্কার পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন এবং ডাক্তার নির্দেশ অনুযায়ী কৃমির ওষুধ নিন। ২–৩ মাস পর Hb পরীক্ষা করুন উন্নতি পর্যবেক্ষণের জন্য।",
        "You have severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Eat iron-rich foods  with vitamin C foods. Take medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.": "আপনার  গুরুতর রক্তাল্পতা হয়েছে, যা বিপজ্জনক এবং জরুরি হাসপাতালে চিকিৎসার প্রয়োজন। ডাক্তার রক্ত দেওয়া (ট্রান্সফিউশন) এবং আয়রন চিকিৎসার পরামর্শ দিতে পারেন। আয়রন সমৃদ্ধ খাবার  সাথে ভিটামিন সি সমৃদ্ধ খাবার  খাবেন। ডাক্তার যে ওষুধ দেবেন তা নিয়ম মেনে খাবেন এবং সব ফলো-আপে যান। ডাক্তারের পরামর্শ অনুযায়ী Hb আবার পরীক্ষা করুন।",
        "You have mild anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.": "আপনার রক্তাল্পতা (হালকা) রয়েছে । সুষম খাবার খান, যা আয়রন সমৃদ্ধ খাবার ও ভিটামিন C সমৃদ্ধ খাবার ।ডাক্তারের পরামর্শ অনুযায়ী আয়রন সাপ্লিমেন্ট নিন। পরিষ্কার পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন এবং ডাক্তার নির্দেশ অনুযায়ী কৃমির ওষুধ নিন। ২–৩ মাস পর Hb পরীক্ষা করুন উন্নতি পর্যবেক্ষণের জন্য।",
        "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods . Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.": "আপনার রক্তের Hb% স্বাভাবিক। সুষম খাবার চালিয়ে যান, যা আয়রন সমৃদ্ধ এবং ভিটামিন সি সমৃদ্ধ .গর্ভাবস্থার জন্য ডাক্তারের পরামর্শ অনুযায়ী আয়রন–ফলিক এসিড সাপ্লিমেন্ট খাওয়া শুরু করুন।  নিয়মিত প্রসব-পূর্ব চেকআপ, টিকা এবং আপনার ও শিশুর স্বাস্থ্যের পর্যবেক্ষণ চালিয়ে যান।",
        "You have mild anemia. Eat a balanced diet with iron-rich foods & vitamin C foods . Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "আপনার  হালকা রক্তাল্পতা রয়েছে। সুষম খাবার খান, যা আয়রন সমৃদ্ধ খাবার ও ভিটামিন সি সমৃদ্ধ খাবার ।ডাক্তার পরামর্শ অনুযায়ী আয়রন–ফলিক এসিড সাপ্লিমেন্ট শুরু বা চালিয়ে যান।  নিরাপদ পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন, পর্যাপ্ত বিশ্রাম নিন এবং নিয়মিত প্রসব-পূর্ব চেকআপ করুন। আপনার এবং শিশুর স্বাস্থ্যের পর্যবেক্ষণ চালিয়ে যান এবং Hb পরীক্ষা ডাক্তার নির্দেশ অনুযায়ী করুন।",
        "You have moderate anemia. Eat a balanced diet with iron-rich foods & vitamin C foods .Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "আপনার মাঝারি পরিমানে রক্তাল্পতা রয়েছে। সুষম খাবার খান, যা আয়রন সমৃদ্ধ খাবার ও ভিটামিন সি সমৃদ্ধ খাবার ।ডাক্তার পরামর্শ অনুযায়ী আয়রন–ফলিক এসিড সাপ্লিমেন্ট শুরু বা চালিয়ে যান।  নিরাপদ পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন, পর্যাপ্ত বিশ্রাম নিন এবং নিয়মিত প্রসব-পূর্ব চেকআপ করুন। আপনার এবং শিশুর স্বাস্থ্যের পর্যবেক্ষণ চালিয়ে যান এবং Hb পরীক্ষা ডাক্তার নির্দেশ অনুযায়ী করুন।",
        "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods  along with vitamin C foods. Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "আপনার  গুরুতর রক্তাল্পতা হয়েছে, যা আপনার এবং আপনার শিশুর জন্য বিপজ্জনক। জরুরি হাসপাতালে চিকিৎসা প্রয়োজন, এবং ডাক্তার রক্ত দেওয়া (ট্রান্সফিউশন) ও শক্তিশালী আয়রন চিকিৎসার পরামর্শ দিতে পারেন। সুষম খাদ্য গ্রহণ করুন, যা আয়রন সমৃদ্ধ   এবং  ভিটামিন সি সমৃদ্ধ খাবার । ডাক্তার যে আয়রন–ফলিক অ্যাসিড বা অন্য ওষুধ দেবেন, তা নিয়মিত সঠিকভাবে গ্রহণ করুন। সব প্রসব-পূর্ব চেকআপে যান এবং ডাক্তারের পরামর্শ অনুযায়ী আবার Hb পরীক্ষা করুন।",
        "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods .Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.": "আপনার রক্তের Hb% স্বাভাবিক। সুষম খাবার চালিয়ে যান, যা আয়রন সমৃদ্ধ খাবার  ভিটামিন C সমৃদ্ধ .গর্ভাবস্থার জন্য ডাক্তারের পরামর্শ অনুযায়ী আয়রন–ফলিক এসিড সাপ্লিমেন্ট খাওয়া শুরু করুন।  নিয়মিত প্রসব-পূর্ব চেকআপ, টিকা এবং আপনার ও শিশুর স্বাস্থ্যের পর্যবেক্ষণ চালিয়ে যান।",
        "You have mild anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "আপনার  হালকা রক্তাল্পতা রয়েছে। সুষম খাবার খান, যা আয়রন সমৃদ্ধ ও  ভিটামিন সি সমৃদ্ধ ।ডাক্তার পরামর্শ অনুযায়ী আয়রন–ফলিক এসিড সাপ্লিমেন্ট শুরু বা চালিয়ে যান। নিরাপদ পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন, পর্যাপ্ত বিশ্রাম নিন এবং নিয়মিত প্রসব-পূর্ব চেকআপ করুন। আপনার এবং শিশুর স্বাস্থ্যের পর্যবেক্ষণ চালিয়ে যান এবং Hb পরীক্ষা ডাক্তার নির্দেশ অনুযায়ী করুন।",
        "You have moderate anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "আপনার মাঝারি পরিমানে রক্তাল্পতা রয়েছে। সুষম খাবার খান, যা আয়রন সমৃদ্ধ ও  ভিটামিন C সমৃদ্ধ। ডাক্তার পরামর্শ অনুযায়ী আয়রন–ফলিক এসিড সাপ্লিমেন্ট শুরু বা চালিয়ে যান। নিরাপদ পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন, পর্যাপ্ত বিশ্রাম নিন এবং নিয়মিত প্রসব-পূর্ব চেকআপ করুন। আপনার এবং শিশুর স্বাস্থ্যের পর্যবেক্ষণ চালিয়ে যান এবং Hb পরীক্ষা ডাক্তার নির্দেশ অনুযায়ী করুন।",
        "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "আপনার  গুরুতর রক্তাল্পতা হয়েছে, যা আপনার এবং আপনার শিশুর জন্য বিপজ্জনক। জরুরি হাসপাতালে চিকিৎসা প্রয়োজন, এবং ডাক্তার রক্ত দেওয়া (ট্রান্সফিউশন) ও শক্তিশালী আয়রন চিকিৎসার পরামর্শ দিতে পারেন। সুষম খাদ্য গ্রহণ করুন, যা আয়রন সমৃদ্ধ , ভিটামিন সি সমৃদ্ধ ।ডাক্তার যে আয়রন–ফলিক অ্যাসিড বা অন্য ওষুধ দেবেন, তা নিয়মিত সঠিকভাবে গ্রহণ করুন। সব প্রসব-পূর্ব চেকআপে যান এবং ডাক্তারের পরামর্শ অনুযায়ী আবার Hb পরীক্ষা করুন।",
        "You have Moderate  anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "আপনার  মাঝারি পরিমানে রক্তাল্পতা রয়েছে। সুষম খাবার খান, যাতে আয়রন সমৃদ্ধ খাবার যেমন মাংস, মাছ, ডিম, ডাল, শিম ও সবজি থাকে। খাবারের সঙ্গে ভিটামিন সি সমৃদ্ধ খাবার ডাক্তার পরামর্শ অনুযায়ী আয়রন–ফলিক এসিড সাপ্লিমেন্ট শুরু বা চালিয়ে যান।  নিরাপদ পানি পান করুন, পরিচ্ছন্নতা বজায় রাখুন, পর্যাপ্ত বিশ্রাম নিন এবং নিয়মিত প্রসব-পূর্ব চেকআপ করুন। আপনার এবং শিশুর স্বাস্থ্যের পর্যবেক্ষণ চালিয়ে যান এবং Hb পরীক্ষা ডাক্তার নির্দেশ অনুযায়ী করুন।",
        "You have severe anemia which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "আপনার  গুরুতর রক্তাল্পতা হয়েছে, যা আপনার এবং আপনার শিশুর জন্য বিপজ্জনক। জরুরি হাসপাতালে চিকিৎসা প্রয়োজন, এবং ডাক্তার রক্ত দেওয়া (ট্রান্সফিউশন) ও শক্তিশালী আয়রন চিকিৎসার পরামর্শ দিতে পারেন। সুষম খাদ্য গ্রহণ করুন, যা আয়রন সমৃদ্ধ , ভিটামিন সি সমৃদ্ধ ।ডাক্তার যে আয়রন–ফলিক অ্যাসিড বা অন্য ওষুধ দেবেন, তা নিয়মিত সঠিকভাবে গ্রহণ করুন। সব প্রসব-পূর্ব চেকআপে যান এবং ডাক্তারের পরামর্শ অনুযায়ী আবার Hb পরীক্ষা করুন।"
      },
      "kn_IN": {
        "Normal": "ಸಾಮಾನ್ಯ",
        "Your child’s HB% level is normal now. Continue breastfeeding up to 2 years and give daily rice/porridge with meat, fish, egg yolk, lentils, vegetables, plus vitamin C foods (orange, guava, tomato) .After 1 year, give deworming medicine (as advised by doctor).": "ನಿಮ್ಮ ಮಗುವಿನ HB% ಮಟ್ಟವು ಈಗ ಸಾಮಾನ್ಯವಾಗಿದೆ. 2 ವರ್ಷಗಳವರೆಗೆ ಎದೆಹಾಲುಣಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿ ಮತ್ತು ಪ್ರತಿದಿನ ಅನ್ನ/ಗಂಜಿ ಮಾಂಸ, ಮೀನು, ಮೊಟ್ಟೆಯ ಹಳದಿ ಭಾಗ, ಬೇಳೆ, ತರಕಾರಿಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ (ಕಿತ್ತಳೆ, ಪೇರಲ, ಟೊಮೆಟೊ) ನೀಡಿ. 1 ವರ್ಷದ ನಂತರ, ಜಂತುಹುಳು ನಿವಾರಣಾ ಔಷಧಿಯನ್ನು ನೀಡಿ (ವೈದ್ಯರು ಸಲಹೆ ನೀಡಿದಂತೆ).",
        "Mild": "ಸೌಮ್ಯ",
        "Your child has mild anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "ನಿಮ್ಮ ಮಗುವಿಗೆ ಸೌಮ್ಯ ರಕ್ತಹೀನತೆ ಇದೆ. 2 ವರ್ಷಗಳವರೆಗೆ ಹಾಲುಣಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿ ಮತ್ತು ಪ್ರತಿದಿನ ಅನ್ನ/ಗಂಜಿಗೆ ಕಬ್ಬಿಣದಂಶವಿರುವ ಆಹಾರಗಳನ್ನು ನೀಡಿ ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳನ್ನು ಸೇರಿಸಿ. ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಸಿರಪ್ ನೀಡಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸುರಕ್ಷಿತ ನೀರು, 1 ವರ್ಷದ ನಂತರ ಜಂತುಹುಳು ನಿವಾರಣೆ ಮಾಡಿ, ಮತ್ತು ಸುಧಾರಣೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು 2-3 ತಿಂಗಳ ನಂತರ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Moderate": "ಮಧ್ಯಮ",
        "Your child has moderate anemia. Continue breastfeeding up to 2 years and give daily rice/porridge with iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "ನಿಮ್ಮ ಮಗುವಿಗೆ ಮಧ್ಯಮ ರಕ್ತಹೀನತೆ ಇದೆ. 2 ವರ್ಷಗಳವರೆಗೆ ಹಾಲುಣಿಸುವುದನ್ನು ಮುಂದುವರಿಸಿ ಮತ್ತು ಪ್ರತಿದಿನ ಅನ್ನ/ಗಂಜಿಗೆ ಕಬ್ಬಿಣದಂಶವಿರುವ ಆಹಾರಗಳನ್ನು ನೀಡಿ ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳನ್ನು ಸೇರಿಸಿ. ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಸಿರಪ್ ನೀಡಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯ, ಸುರಕ್ಷಿತ ನೀರು, 1 ವರ್ಷದ ನಂತರ ಜಂತುಹುಳು ನಿವಾರಣೆ ಮತ್ತು ಸುಧಾರಣೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು 2-3 ತಿಂಗಳ ನಂತರ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Severe": "ತೀವ್ರ",
        "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Continue breastfeeding and give iron-rich foods  with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.": "ನಿಮ್ಮ ಮಗುವಿಗೆ ತೀವ್ರ ರಕ್ತಹೀನತೆ ಇದೆ, ಇದು ಅಪಾಯಕಾರಿ ಮತ್ತು ತುರ್ತು ಆಸ್ಪತ್ರೆ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ. ವೈದ್ಯರು ರಕ್ತ ವರ್ಗಾವಣೆ ಮತ್ತು ಕಬ್ಬಿಣದ ಚಿಕಿತ್ಸೆಯನ್ನು ಸೂಚಿಸಬಹುದು. ಸ್ತನ್ಯಪಾನವನ್ನು ಮುಂದುವರಿಸಿ ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಕಬ್ಬಿಣದ ಭರಿತ ಆಹಾರವನ್ನು ನೀಡಿ. ಸೂಚಿಸಿದ ಔಷಧಿಗಳನ್ನು ನಿಖರವಾಗಿ ನೀಡಿ ಮತ್ತು ಎಲ್ಲಾ ನಂತರದ ಭೇಟಿಗಳಿಗೆ ಹಾಜರಾಗಿ. ವೈದ್ಯರು ನಿರ್ದೇಶಿಸಿದಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your child’s HB% level is normal. Give 3 meals and 1–2 healthy snacks daily with iron-rich foods & Add vitamin C foods  with meals.Avoid junk food, and excess cow’s milk .Maintain handwashing, safe water, and good hygiene, and give deworming medicine every 6 months as advised by the doctor.": "ನಿಮ್ಮ ಮಗುವಿನ HB% ಮಟ್ಟವು ಸಾಮಾನ್ಯವಾಗಿದೆ. ಪ್ರತಿದಿನ 3 ಊಟಗಳು ಮತ್ತು 1-2 ಆರೋಗ್ಯಕರ ತಿಂಡಿಗಳನ್ನು ಕಬ್ಬಿಣದ ಅಂಶವಿರುವ ಆಹಾರಗಳೊಂದಿಗೆ ನೀಡಿ ಮತ್ತು ಊಟದೊಂದಿಗೆ ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳನ್ನು ಸೇರಿಸಿ. ಜಂಕ್ ಫುಡ್ ಮತ್ತು ಹೆಚ್ಚುವರಿ ಹಸುವಿನ ಹಾಲನ್ನು ತಪ್ಪಿಸಿ. ಕೈ ತೊಳೆಯುವುದು, ಸುರಕ್ಷಿತ ನೀರು ಮತ್ತು ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ ಮತ್ತು ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಪ್ರತಿ 6 ತಿಂಗಳಿಗೊಮ್ಮೆ ಜಂತುಹುಳು ನಿವಾರಣಾ ಔಷಧಿಯನ್ನು ನೀಡಿ.",
        "Your child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.": "ನಿಮ್ಮ ಮಗುವಿಗೆ ತೀವ್ರ ರಕ್ತಹೀನತೆ ಇದೆ, ಇದು ಅಪಾಯಕಾರಿ ಮತ್ತು ತುರ್ತು ಆಸ್ಪತ್ರೆ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ. ವೈದ್ಯರು ರಕ್ತ ವರ್ಗಾವಣೆ ಮತ್ತು ಕಬ್ಬಿಣದ ಚಿಕಿತ್ಸೆಯನ್ನು ಸೂಚಿಸಬಹುದು. ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಕಬ್ಬಿಣದ ಭರಿತ ಆಹಾರವನ್ನು ನೀಡಿ. ಸೂಚಿಸಿದ ಔಷಧಿಗಳನ್ನು ನಿಖರವಾಗಿ ನೀಡಿ ಮತ್ತು ಎಲ್ಲಾ ನಂತರದ ಭೇಟಿಗಳಿಗೆ ಹಾಜರಾಗಿ. . ವೈದ್ಯರು ನಿರ್ದೇಶಿಸಿದಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your child’s Hb% level is normal. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods  Limit junk food, tea, and excess cow’s milk. Maintain good hygiene, handwashing, safe drinking water, and give deworming medicine as advised by the doctor.": "ನಿಮ್ಮ ಮಗುವಿನ Hb% ಮಟ್ಟವು ಸಾಮಾನ್ಯವಾಗಿದೆ. ಪ್ರತಿದಿನ 3 ಸಮತೋಲಿತ ಊಟ ಮತ್ತು ಕಬ್ಬಿಣಾಂಶವಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳು ಸೇರಿದಂತೆ ಆರೋಗ್ಯಕರ ತಿಂಡಿಗಳನ್ನು ನೀಡಿ. ಜಂಕ್ ಫುಡ್, ಚಹಾ ಮತ್ತು ಹೆಚ್ಚುವರಿ ಹಸುವಿನ ಹಾಲನ್ನು ಮಿತಿಗೊಳಿಸಿ. ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಕೈ ತೊಳೆಯುವುದು, ಸುರಕ್ಷಿತ ಕುಡಿಯುವ ನೀರು ಮತ್ತು ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಜಂತುಹುಳು ನಿವಾರಣಾ ಔಷಧಿಯನ್ನು ನೀಡಿ.",
        "Your child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "ನಿಮ್ಮ ಮಗುವಿಗೆ ಸೌಮ್ಯ ರಕ್ತಹೀನತೆ ಇದೆ. ಪ್ರತಿದಿನ 3 ಸಮತೋಲಿತ ಊಟ ಮತ್ತು ಆರೋಗ್ಯಕರ ತಿಂಡಿಗಳನ್ನು ನೀಡಿ, ಅದರಲ್ಲಿ ಕಬ್ಬಿಣದ ಅಂಶವಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳನ್ನು ಸೇರಿಸಿ. ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಸಿರಪ್ ನೀಡಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯ, ಸುರಕ್ಷಿತ ನೀರು, 1 ವರ್ಷದ ನಂತರ ಜಂತುಹುಳು ನಿವಾರಣೆ ಮತ್ತು ಸುಧಾರಣೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು 2-3 ತಿಂಗಳ ನಂತರ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & add vitamin C foods . Give iron syrup as prescribed by the doctor, maintain good hygiene, safe water, deworming after 1 year, and recheck Hb after 2–3 months to monitor improvement.": "ನಿಮ್ಮ ಮಗುವಿಗೆ ಮಧ್ಯಮ ರಕ್ತಹೀನತೆ ಇದೆ. ಪ್ರತಿದಿನ 3 ಸಮತೋಲಿತ ಊಟ ಮತ್ತು ಆರೋಗ್ಯಕರ ತಿಂಡಿಗಳನ್ನು ನೀಡಿ, ಅದರಲ್ಲಿ ಕಬ್ಬಿಣದ ಅಂಶವಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳನ್ನು ಸೇರಿಸಿ. ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಸಿರಪ್ ನೀಡಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯ, ಸುರಕ್ಷಿತ ನೀರು, 1 ವರ್ಷದ ನಂತರ ಜಂತುಹುಳು ನಿವಾರಣೆ ಮತ್ತು ಸುಧಾರಣೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು 2-3 ತಿಂಗಳ ನಂತರ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your child's  Hb% level is normal। Encourage 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods.  Maintain good hygiene, regular physical activity, and follow deworming advice as recommended by the doctor. ": "ನಿಮ್ಮ ಮಗುವಿನ Hb% ಮಟ್ಟವು ಸಾಮಾನ್ಯವಾಗಿದೆ. ಕಬ್ಬಿಣಾಂಶವಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳು ಸೇರಿದಂತೆ ಪ್ರತಿದಿನ 3 ಸಮತೋಲಿತ ಊಟ ಮತ್ತು ಆರೋಗ್ಯಕರ ತಿಂಡಿಗಳನ್ನು ಸೇವಿಸಲು ಪ್ರೋತ್ಸಾಹಿಸಿ. ಉತ್ತಮ ನೈರ್ಮಲ್ಯ, ನಿಯಮಿತ ದೈಹಿಕ ಚಟುವಟಿಕೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ ಮತ್ತು ವೈದ್ಯರು ಶಿಫಾರಸು ಮಾಡಿದಂತೆ ಜಂತುಹುಳು ನಿವಾರಣಾ ಸಲಹೆಯನ್ನು ಅನುಸರಿಸಿ.",
        "Your  child has mild anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement": "ನಿಮ್ಮ ಮಗುವಿಗೆ ಸೌಮ್ಯ ರಕ್ತಹೀನತೆ ಇದೆ. ಪ್ರತಿದಿನ 3 ಸಮತೋಲಿತ ಊಟ ಮತ್ತು ಆರೋಗ್ಯಕರ ತಿಂಡಿಗಳನ್ನು ನೀಡಿ, ಅದರಲ್ಲಿ ಕಬ್ಬಿಣದ ಅಂಶವಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳು ಸೇರಿವೆ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಸಿರಪ್ ಅಥವಾ ಪೂರಕಗಳನ್ನು ನೀಡಿ. ಉತ್ತಮ ನೈರ್ಮಲ್ಯ, ಸುರಕ್ಷಿತ ನೀರು, ಸಲಹೆಯಂತೆ ಜಂತುಹುಳು ನಿವಾರಣೆ ಮತ್ತು ಬೆಳವಣಿಗೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ. ಸುಧಾರಣೆ ಕಾಣಲು 2–3 ತಿಂಗಳ ನಂತರ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your  child has moderate anemia. Give 3 balanced meals and healthy snacks daily, including iron-rich foods & vitamin C foods. Give iron syrup or supplements as prescribed by your doctor. Ensure good hygiene, safe water, deworming as advised, and monitor growth. Recheck Hb after 2–3 months to see improvement": "ನಿಮ್ಮ ಮಗುವಿಗೆ ಮಧ್ಯಮ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣದ ಅಂಶವಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳು ಸೇರಿದಂತೆ ಪ್ರತಿದಿನ 3 ಸಮತೋಲಿತ ಊಟ ಮತ್ತು ಆರೋಗ್ಯಕರ ತಿಂಡಿಗಳನ್ನು ನೀಡಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಸಿರಪ್ ಅಥವಾ ಪೂರಕಗಳನ್ನು ನೀಡಿ. ಉತ್ತಮ ನೈರ್ಮಲ್ಯ, ಸುರಕ್ಷಿತ ನೀರು, ಸಲಹೆಯಂತೆ ಜಂತುಹುಳು ನಿವಾರಣೆ ಮತ್ತು ಬೆಳವಣಿಗೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ. ಸುಧಾರಣೆ ಕಾಣಲು 2–3 ತಿಂಗಳ ನಂತರ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your  child has severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Give iron-rich foods with vitamin C foods. Give medicines exactly as prescribed and attend all follow-up visits. . Recheck Hb as directed by the doctor.": "ನಿಮ್ಮ ಮಗುವಿಗೆ ತೀವ್ರ ರಕ್ತಹೀನತೆ ಇದೆ, ಇದು ಅಪಾಯಕಾರಿ ಮತ್ತು ತುರ್ತು ಆಸ್ಪತ್ರೆ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ. ವೈದ್ಯರು ರಕ್ತ ವರ್ಗಾವಣೆ ಮತ್ತು ಕಬ್ಬಿಣದ ಚಿಕಿತ್ಸೆಯನ್ನು ಸೂಚಿಸಬಹುದು. ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಕಬ್ಬಿಣದ ಭರಿತ ಆಹಾರವನ್ನು ನೀಡಿ. ಸೂಚಿಸಿದ ಔಷಧಿಗಳನ್ನು ನಿಖರವಾಗಿ ನೀಡಿ ಮತ್ತು ಎಲ್ಲಾ ನಂತರದ ಭೇಟಿಗಳಿಗೆ ಹಾಜರಾಗಿ. . ವೈದ್ಯರು ನಿರ್ದೇಶಿಸಿದಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your blood hb% level is normal. Maintain a balanced diet with iron-rich foods &  vitamin C foods. Practice good hygiene, stay physically active, and follow deworming advice if recommended by your doctor.": "ನಿಮ್ಮ ರಕ್ತದ hb% ಮಟ್ಟವು ಸಾಮಾನ್ಯವಾಗಿದೆ. ಕಬ್ಬಿಣಾಂಶವಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ. ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ, ದೈಹಿಕವಾಗಿ ಸಕ್ರಿಯರಾಗಿರಿ ಮತ್ತು ನಿಮ್ಮ ವೈದ್ಯರು ಶಿಫಾರಸು ಮಾಡಿದರೆ ಜಂತುಹುಳು ನಿವಾರಣಾ ಸಲಹೆಯನ್ನು ಅನುಸರಿಸಿ.",
        "Your hemoglobin is Mild high than normal. Stay well-hydrated, avoid unnecessary iron supplements, and consult a doctor for proper evaluation.": "ನಿಮ್ಮ ಹಿಮೋಗ್ಲೋಬಿನ್ ಸಾಮಾನ್ಯಕ್ಕಿಂತ ಸ್ವಲ್ಪ ಹೆಚ್ಚಾಗಿದೆ. ಚೆನ್ನಾಗಿ ಹೈಡ್ರೇಟೆಡ್ ಆಗಿರಿ, ಅನಗತ್ಯ ಕಬ್ಬಿಣದ ಪೂರಕಗಳನ್ನು ತಪ್ಪಿಸಿ ಮತ್ತು ಸರಿಯಾದ ಮೌಲ್ಯಮಾಪನಕ್ಕಾಗಿ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        "You have moderate anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.": "ನಿಮಗೆ ಮಧ್ಯಮ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಪೂರಕಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ. ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸುರಕ್ಷಿತ ನೀರನ್ನು ಕುಡಿಯಿರಿ ಮತ್ತು ಶಿಫಾರಸು ಮಾಡಿದರೆ ಜಂತುಹುಳು ನಿವಾರಣಾ ಸಲಹೆಯನ್ನು ಅನುಸರಿಸಿ. ಸುಧಾರಣೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು 2-3 ತಿಂಗಳ ನಂತರ Hb ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have severe anemia, which is dangerous and needs urgent hospital care. The doctor may advise blood transfusion and iron treatment. Eat iron-rich foods  with vitamin C foods. Take medicines exactly as prescribed and attend all follow-up visits. Recheck Hb as directed by the doctor.": "ನಿಮಗೆ ತೀವ್ರ ರಕ್ತಹೀನತೆ ಇದೆ, ಇದು ಅಪಾಯಕಾರಿ ಮತ್ತು ತುರ್ತು ಆಸ್ಪತ್ರೆ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ. ವೈದ್ಯರು ರಕ್ತ ವರ್ಗಾವಣೆ ಮತ್ತು ಕಬ್ಬಿಣದ ಚಿಕಿತ್ಸೆಗೆ ಸಲಹೆ ನೀಡಬಹುದು. ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಕಬ್ಬಿಣದ ಭರಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ಸೂಚಿಸಿದಂತೆ ನಿಖರವಾಗಿ ಔಷಧಿಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ ಮತ್ತು ಎಲ್ಲಾ ನಂತರದ ಭೇಟಿಗಳಿಗೆ ಹಾಜರಾಗಿ. ವೈದ್ಯರು ನಿರ್ದೇಶಿಸಿದಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have mild anemia.Eat a balanced diet including iron-rich foods & vitamin C foods . Take iron supplements as prescribed by your doctor. Maintain good hygiene, drink safe water, and follow deworming advice if recommended. Recheck Hb after 2–3 months to monitor improvement.": "ನಿಮಗೆ ಸೌಮ್ಯ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣಾಂಶ ಹೆಚ್ಚಿರುವ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣದ ಪೂರಕಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ. ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸುರಕ್ಷಿತ ನೀರನ್ನು ಕುಡಿಯಿರಿ ಮತ್ತು ಶಿಫಾರಸು ಮಾಡಿದರೆ ಜಂತುಹುಳು ನಿವಾರಣಾ ಸಲಹೆಯನ್ನು ಅನುಸರಿಸಿ. ಸುಧಾರಣೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು 2-3 ತಿಂಗಳ ನಂತರ Hb ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods . Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.": "ನಿಮ್ಮ ರಕ್ತದ Hb% ಮಟ್ಟವು ಸಾಮಾನ್ಯವಾಗಿದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಮುಂದುವರಿಸಿ. ನಿಮ್ಮ ಗರ್ಭಧಾರಣೆಯನ್ನು ಬೆಂಬಲಿಸಲು ನಿಮ್ಮ ವೈದ್ಯರು ಸಲಹೆ ನೀಡಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲ ಪೂರಕಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಪ್ರಾರಂಭಿಸಿ. ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆ, ವ್ಯಾಕ್ಸಿನೇಷನ್‌ಗಳು ಮತ್ತು ನಿಮ್ಮ ಆರೋಗ್ಯ ಮತ್ತು ಮಗುವಿನ ಬೆಳವಣಿಗೆಯ ನಿಯಮಿತ ಮೇಲ್ವಿಚಾರಣೆಯನ್ನು ಮುಂದುವರಿಸಿ.",
        "You have mild anemia. Eat a balanced diet with iron-rich foods & vitamin C foods . Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "ನಿಮಗೆ ಸೌಮ್ಯ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲದ ಪೂರಕಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ ಅಥವಾ ಮುಂದುವರಿಸಿ. ಸುರಕ್ಷಿತ ನೀರು ಕುಡಿಯಿರಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸಾಕಷ್ಟು ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ ಮತ್ತು ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ. ನಿಮ್ಮ ಆರೋಗ್ಯ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿನ ಬೆಳವಣಿಗೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಸಲಹೆಯಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have moderate anemia. Eat a balanced diet with iron-rich foods & vitamin C foods .Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "ನಿಮಗೆ ಮಧ್ಯಮ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲದ ಪೂರಕಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ ಅಥವಾ ಮುಂದುವರಿಸಿ. ಸುರಕ್ಷಿತ ನೀರು ಕುಡಿಯಿರಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸಾಕಷ್ಟು ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ ಮತ್ತು ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ. ನಿಮ್ಮ ಆರೋಗ್ಯ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿನ ಬೆಳವಣಿಗೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಸಲಹೆಯಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods  along with vitamin C foods. Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "ನಿಮಗೆ ತೀವ್ರ ರಕ್ತಹೀನತೆ ಇದೆ, ಇದು ನಿಮಗೆ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿಗೆ ಅಪಾಯಕಾರಿ. ನಿಮಗೆ ತುರ್ತು ಆಸ್ಪತ್ರೆ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ ಮತ್ತು ವೈದ್ಯರು ರಕ್ತ ವರ್ಗಾವಣೆ ಮತ್ತು ಬಲವಾದ ಕಬ್ಬಿಣದ ಚಿಕಿತ್ಸೆಯನ್ನು ಸೂಚಿಸಬಹುದು. ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲ ಅಥವಾ ಇತರ ಔಷಧಿಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ, ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ ಮತ್ತು ನಿಮ್ಮ ವೈದ್ಯರು ನಿರ್ದೇಶಿಸಿದಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "Your blood Hb% level is normal. Continue a balanced diet with iron-rich foods & vitamin C foods .Start taking iron–folic acid supplements as advised by your doctor to support your pregnancy.  Keep up with antenatal check-ups, vaccinations, and regular monitoring of your health and baby’s growth.": "ನಿಮ್ಮ ರಕ್ತದ Hb% ಮಟ್ಟವು ಸಾಮಾನ್ಯವಾಗಿದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಮುಂದುವರಿಸಿ. ನಿಮ್ಮ ಗರ್ಭಧಾರಣೆಯನ್ನು ಬೆಂಬಲಿಸಲು ನಿಮ್ಮ ವೈದ್ಯರು ಸಲಹೆ ನೀಡಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲ ಪೂರಕಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಲು ಪ್ರಾರಂಭಿಸಿ. ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆ, ವ್ಯಾಕ್ಸಿನೇಷನ್‌ಗಳು ಮತ್ತು ನಿಮ್ಮ ಆರೋಗ್ಯ ಮತ್ತು ಮಗುವಿನ ಬೆಳವಣಿಗೆಯ ನಿಯಮಿತ ಮೇಲ್ವಿಚಾರಣೆಯನ್ನು ಮುಂದುವರಿಸಿ.",
        "You have mild anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "ನಿಮಗೆ ಸೌಮ್ಯ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲದ ಪೂರಕಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ ಅಥವಾ ಮುಂದುವರಿಸಿ. ಸುರಕ್ಷಿತ ನೀರು ಕುಡಿಯಿರಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸಾಕಷ್ಟು ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ ಮತ್ತು ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ. ನಿಮ್ಮ ಆರೋಗ್ಯ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿನ ಬೆಳವಣಿಗೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಸಲಹೆಯಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have moderate anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "ನಿಮಗೆ ಮಧ್ಯಮ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲದ ಪೂರಕಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ ಅಥವಾ ಮುಂದುವರಿಸಿ. ಸುರಕ್ಷಿತ ನೀರು ಕುಡಿಯಿರಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸಾಕಷ್ಟು ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ ಮತ್ತು ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ. ನಿಮ್ಮ ಆರೋಗ್ಯ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿನ ಬೆಳವಣಿಗೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಸಲಹೆಯಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have severe anemia  which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "ನಿಮಗೆ ತೀವ್ರ ರಕ್ತಹೀನತೆ ಇದೆ, ಇದು ನಿಮಗೆ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿಗೆ ಅಪಾಯಕಾರಿ. ನಿಮಗೆ ತುರ್ತು ಆಸ್ಪತ್ರೆ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ ಮತ್ತು ವೈದ್ಯರು ರಕ್ತ ವರ್ಗಾವಣೆ ಮತ್ತು ಬಲವಾದ ಕಬ್ಬಿಣದ ಚಿಕಿತ್ಸೆಯನ್ನು ಸೂಚಿಸಬಹುದು. ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲ ಅಥವಾ ಇತರ ಔಷಧಿಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ, ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ ಮತ್ತು ನಿಮ್ಮ ವೈದ್ಯರು ನಿರ್ದೇಶಿಸಿದಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have Moderate  anemia . Eat a balanced diet with iron-rich foods & vitamin C foods. Start or continue iron–folic acid supplements as prescribed by your doctor. Drink safe water, maintain good hygiene, get adequate rest, and attend all antenatal check-ups. Monitor your health and your baby’s growth, and recheck Hb as advised.": "ನಿಮಗೆ ಮಧ್ಯಮ ರಕ್ತಹೀನತೆ ಇದೆ. ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳು ಮತ್ತು ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ನಿಮ್ಮ ವೈದ್ಯರು ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲದ ಪೂರಕಗಳನ್ನು ಪ್ರಾರಂಭಿಸಿ ಅಥವಾ ಮುಂದುವರಿಸಿ. ಸುರಕ್ಷಿತ ನೀರು ಕುಡಿಯಿರಿ, ಉತ್ತಮ ನೈರ್ಮಲ್ಯವನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಿ, ಸಾಕಷ್ಟು ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ ಮತ್ತು ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ. ನಿಮ್ಮ ಆರೋಗ್ಯ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿನ ಬೆಳವಣಿಗೆಯನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಸಲಹೆಯಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ.",
        "You have severe anemia which is dangerous for both you and your baby. You need urgent hospital care, and the doctor may advise blood transfusion and strong iron treatment. Eat a balanced diet with iron-rich foods along with vitamin C foods.Take iron–folic acid or other medicines exactly as prescribed, attend all antenatal check-ups, and recheck Hb as directed by your doctor.": "ನಿಮಗೆ ತೀವ್ರ ರಕ್ತಹೀನತೆ ಇದೆ, ಇದು ನಿಮಗೆ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿಗೆ ಅಪಾಯಕಾರಿ. ನಿಮಗೆ ತುರ್ತು ಆಸ್ಪತ್ರೆ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ ಮತ್ತು ವೈದ್ಯರು ರಕ್ತ ವರ್ಗಾವಣೆ ಮತ್ತು ಬಲವಾದ ಕಬ್ಬಿಣದ ಚಿಕಿತ್ಸೆಯನ್ನು ಸೂಚಿಸಬಹುದು. ವಿಟಮಿನ್ ಸಿ ಆಹಾರಗಳೊಂದಿಗೆ ಕಬ್ಬಿಣ-ಭರಿತ ಆಹಾರಗಳೊಂದಿಗೆ ಸಮತೋಲಿತ ಆಹಾರವನ್ನು ಸೇವಿಸಿ. ಸೂಚಿಸಿದಂತೆ ಕಬ್ಬಿಣ-ಫೋಲಿಕ್ ಆಮ್ಲ ಅಥವಾ ಇತರ ಔಷಧಿಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ, ಎಲ್ಲಾ ಪ್ರಸವಪೂರ್ವ ತಪಾಸಣೆಗಳಿಗೆ ಹಾಜರಾಗಿ ಮತ್ತು ನಿಮ್ಮ ವೈದ್ಯರು ನಿರ್ದೇಶಿಸಿದಂತೆ ಹಿಮೋಗ್ಲೋಬಿನ್ ಅನ್ನು ಮರುಪರಿಶೀಲಿಸಿ."
      }
    };

  }

  @override
  String getRouteName() {
    return routeName;
  }

  @override
  void loadDependentLogics() {

    Get.put(ScreeningReportRepository());
    Get.put(HemoglobinInputLogic(repository: Get.find<ScreeningReportRepository>()));
  }
}
